import Head from "next/head";
import Router from "next/router";

export default function Home() {
  const handleClick = (props) => {
    console.log(props);
    Router.push(props);
  };
  return (
    <>
      <Head>
        <title>PatientNav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <div className="grid grid-rows-2 gap-5 md: grid-cols-2">
          <button onClick={() => handleClick("/User")}>USER</button>
          <button onClick={() => handleClick("/Hospital")}>HOSPITAL</button>
        </div>
      </main>
    </>
  );
}
